---
  - name: Print os facts
    hosts: all
    tasks:
      - name: Print OS
        debug:
          msg: "{{ ansible_distribution }}"
      - name: Print fact
        debug:
          msg: "{{ some_fact }}"
      - name: Print hellow
        when:
          inventory_hostname == 'fedora'
        debug:
          msg: "{{ hello }}"
